### ISSUE TITLE
请教修改WebHook....

### ISSUE THREAD

**Issue by wxlost** [Git-Lofter/game-bot#1]
```
修改telegram bot WebHook为update.php。
```
这句没看懂....

**Comment by 18751238155** [comment]
bot token=TOKEN
update.php所在位置=WWW
访问https://api.telegram.org/botTOKEN/setWebhook?url=WWW
网站必须开启ssl   替换以下就可以了

**Comment by fxs000** [comment]
全部设置好后，机器人私聊或在群里发命令都没有任何反应是哪里出错了

**Comment by aiastia** [comment]
这些文件是放在那个目录里面   {"ok":false,"error_code":404,"description":"Not Found"} 
我在public 里面新建一个 目录的  然后 https://api.telegram.org/botTOKEN/setWebhook?url=xxx.com/gmae-bot/update.php
